language: r
sudo: false
cache: packages
env:
  global:
  - secure: zrXCZ9QYE14nzwP3OdpXzHGXr4bfPYznfdzK/FVL828l4fvcdsq/oAuAzdubBv+hcmgikCwjmZfnzoO8LbYBV8BdbqC8faTpOGhhg6DgIwV0EOhlks6/fyG91UKM4K+0bPhhLVY9Asu4Xg4GOFEEcmnt6bgXvYWm/q80AblZybkeECo2LAp+c4xEolvA9ue4jVa6FSqCWdXgNPKaCXyYpg/KPvYKo7fpe/XVFFJwMDYShPdAiATVRf9h4020/yM7kz2Qgtw3OV1kBfGhfRulOP6/dAWetIBVZzaL1sJO3+jznQan4IRInICQjtQcpZBd3lo+jO1RRFeUWuaO3r343oc/sJUjo5uTLkVOvjDDQYfqn2K1WSaaZxsKlOtPHBGQHarJu1LHllBRvnWZJGSiFPhsoDEZ69XD0J7JLNFtziIPlqCb+7g9IanlC/fSYPEsi3Nq7gNtOkHt5m/wKlXVuOdhD5qc+/6B8GwBTU9+RG9710f6s/v67EGNCpQa1Z6sN9DhjF6AA2hBDm0Ntlquj4xyYm/TcvKYOAbN8o3TjaFL4TNAtHXmuaq+t+vqgrlnrZF0BLjWj2vcRM0DSci7P8I9wdccsqurjRHHuFxqFjOWfJCwVldqoYhDhBR7NRBcy+fgjw1wpSZR6El1Y3BwA9UpH0nwNnfRUV7dKoySPWQ=
r_github_packages:
- rstudio/rmarkdown
install:
- R -e "install.packages('devtools')"
- R -e "devtools::install_github('rstudio/rmarkdown')"
script:
- R -e "rmarkdown::render_site()"
- tools/pdf_full info1_lab01.md
after_success:
- ./tools/deploy.sh
